src/Samples/WebSample/Controllers/EmailController.cs
using System;
using System.Web.Mvc;
using Postal;

namespace WebSample.Controllers
{
    public class EmailController : Controller
    {
        [HttpPost]
        public ActionResult SendSimple()
        {
            dynamic email = new EmailTemplate("Simple");
            email.Date = DateTime.UtcNow.ToString();
            email.Send();

            return RedirectToAction("Sent", "Home");
        }

        [HttpPost]
        public ActionResult SendMultiPart()
        {
            dynamic email = new EmailTemplate("MultiPart");
            email.Date = DateTime.UtcNow.ToString();
            email.Send();

            return RedirectToAction("Sent", "Home");
        }
    }

    public class TypedTemplate : Template
    {
        public string Date { get; set; }
        public override string ViewName { get; set; }
    }
}

src/Samples/WebSample/Controllers/PreviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Postal;

namespace WebSample.Controllers
{
    public class PreviewController : Controller
    {
        public ActionResult Simple()
        {
            dynamic email = new EmailTemplate("Simple");
            email.Date = DateTime.UtcNow.ToString();
            
            return new TemplateViewResult(email);
        }

        public ActionResult SimpleHtml()
        {
            dynamic email = new EmailTemplate("SimpleHtml");
            email.Date = DateTime.UtcNow.ToString();

            return new TemplateViewResult(email);
        }
        
        public ActionResult MultiPart()
        {
            dynamic email = new EmailTemplate("MultiPart");
            email.Date = DateTime.UtcNow.ToString();
            
            return new TemplateViewResult(email);
        }

        public ActionResult Typed()
        {
            var email = new TypedTemplate();
            email.Date = DateTime.UtcNow.ToString();
            
            return new TemplateViewResult(email);
        }
    }
}

src/Samples/WebSample/Views/Home/Index.cshtml
<h1>Postal Samples</h1>
<p>
    Before running these samples, please start the SMTP development server,
    found in the Postal code directory: <code>tools\smtp4dev.exe</code>
</p>
<p>
    Use the SMTP development server to inspect the contents of generated Template (headers, content, etc).
    No Template is really sent, so it's perfect for debugging.
</p>
<p>
    <a href="@Url.Action("Samples")" class="btn btn-primary">Continue &raquo;</a>
</p>

src/Samples/WebSample/Views/Home/Samples.cshtml
<h1>Postal Samples</h1>

<p>
    The send buttons on this page post to <code>Controllers\TemplateController.cs</code><br/>
    The preview buttons on this page go to <code>Controllers\PreviewController.cs</code>
</p>

<h2>Sending a basic Template</h2>
<p>Template will be generated from <code>Views\Template\Simple.cshtml</code></p>
<form action="@Url.Action("SendSimple", "Email")" method="POST">
    <button type="submit" class="btn btn-primary">Send Template</button>
    <a href="@Url.Action("Simple", "Preview")" class="btn btn-default">Preview</a>
</form>

<h2>Strongly-typed Template class</h2>
<p>Template will be generated from <code>Views\Template\Typed.cshtml</code></p>
<form action="@Url.Action("SendTypedEmail", "Email")" method="POST">
    <button type="submit" class="btn btn-primary">Send Template</button>
    <a href="@Url.Action("Typed", "Preview")" class="btn btn-default">Preview</a>
</form>

<h2>Multipart emails</h2>
<p>
    Use separate views to define HTML and plain-text content for a single Template.
</p>
<pre>Views\Template\Simple.cshtml
Views\Template\Simple.Html.cshtml
Views\Template\Simple.Text.cshtml</pre>
<p>
    Images can be embedded into the Template using <code>@@Html.EmbedImage("~/image.png")</code>.
</p>
<form action="@Url.Action("SendMultiPart", "Email")" method="POST">
    <button type="submit" class="btn btn-primary">Send Template</button>
    <a href="@Url.Action("MultiPart", "Preview")" class="btn btn-default">Preview</a>
    <a href="@Url.Action("MultiPart", "Preview", new { format = "text"})" class="btn btn-default">Preview Text</a>
    <a href="@Url.Action("MultiPart", "Preview", new { format = "html" })" class="btn btn-default">Preview Html</a>
</form>

src/Samples/WebSample/Views/Home/Sent.cshtml
<h1>Template Sent</h1>
<p>
    <a href="@Url.Action("Samples")" class="btn btn-primary">Continue &raquo;</a>
</p>